/* 
 * speechapi
 *
 * Speech APIs enable you to recognize speech and convert it to text using advanced machine learning, and also to convert text to speech.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.Speech.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.Speech.Model
{
    /// <summary>
    /// Result of recognizing speech with the higher-accuracy file/advanced endpoint.  Word-oriented (one entry per word, not per BPE sub-token) and produced  from DTW-aligned timestamps.
    /// </summary>
    [DataContract]
    public partial class SpeechRecognitionResultAdvanced :  IEquatable<SpeechRecognitionResultAdvanced>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SpeechRecognitionResultAdvanced" /> class.
        /// </summary>
        /// <param name="textResult">Recognition result in text format.</param>
        /// <param name="words">Word-level timestamps with character offsets into TextResult.  Timestamps are derived via Dynamic Time Warping (DTW) alignment for  substantially better accuracy than the default token-timestamp path..</param>
        public SpeechRecognitionResultAdvanced(string textResult = default(string), List<WordTimestamp> words = default(List<WordTimestamp>))
        {
            this.TextResult = textResult;
            this.Words = words;
        }
        
        /// <summary>
        /// Recognition result in text format
        /// </summary>
        /// <value>Recognition result in text format</value>
        [DataMember(Name="TextResult", EmitDefaultValue=false)]
        public string TextResult { get; set; }

        /// <summary>
        /// Word-level timestamps with character offsets into TextResult.  Timestamps are derived via Dynamic Time Warping (DTW) alignment for  substantially better accuracy than the default token-timestamp path.
        /// </summary>
        /// <value>Word-level timestamps with character offsets into TextResult.  Timestamps are derived via Dynamic Time Warping (DTW) alignment for  substantially better accuracy than the default token-timestamp path.</value>
        [DataMember(Name="Words", EmitDefaultValue=false)]
        public List<WordTimestamp> Words { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SpeechRecognitionResultAdvanced {\n");
            sb.Append("  TextResult: ").Append(TextResult).Append("\n");
            sb.Append("  Words: ").Append(Words).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SpeechRecognitionResultAdvanced);
        }

        /// <summary>
        /// Returns true if SpeechRecognitionResultAdvanced instances are equal
        /// </summary>
        /// <param name="input">Instance of SpeechRecognitionResultAdvanced to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SpeechRecognitionResultAdvanced input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TextResult == input.TextResult ||
                    (this.TextResult != null &&
                    this.TextResult.Equals(input.TextResult))
                ) && 
                (
                    this.Words == input.Words ||
                    this.Words != null &&
                    this.Words.SequenceEqual(input.Words)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TextResult != null)
                    hashCode = hashCode * 59 + this.TextResult.GetHashCode();
                if (this.Words != null)
                    hashCode = hashCode * 59 + this.Words.GetHashCode();
                return hashCode;
            }
        }
    }

}
