/* 
 * speechapi
 *
 * Speech APIs enable you to recognize speech and convert it to text using advanced machine learning, and also to convert text to speech.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.Speech.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.Speech.Model
{
    /// <summary>
    /// Result of performing a Speech batch job operation
    /// </summary>
    [DataContract]
    public partial class SpeechBatchJobStatusResult :  IEquatable<SpeechBatchJobStatusResult>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SpeechBatchJobStatusResult" /> class.
        /// </summary>
        /// <param name="successful">True if the operation to check the status of the job was successful, false otherwise.</param>
        /// <param name="asyncJobStatus">Returns the job status of the Async Job, if applicable.  Possible states are STARTED and COMPLETED.</param>
        /// <param name="asyncJobID">Job ID.</param>
        /// <param name="recognizeResult">recognizeResult.</param>
        /// <param name="recognizeAdvancedResult">recognizeAdvancedResult.</param>
        /// <param name="speakAudioResultFileContent">Generated audio file produced by a completed Text-to-Speech batch job, in the requested format (mp3 or wav).</param>
        /// <param name="speakAudioContentType">MIME type of SpeakAudioResultFileContent (audio/mpeg or audio/wav).</param>
        /// <param name="errorMessage">Error message (if any).</param>
        public SpeechBatchJobStatusResult(bool? successful = default(bool?), string asyncJobStatus = default(string), string asyncJobID = default(string), SpeechRecognitionResult recognizeResult = default(SpeechRecognitionResult), SpeechRecognitionResultAdvanced recognizeAdvancedResult = default(SpeechRecognitionResultAdvanced), byte[] speakAudioResultFileContent = default(byte[]), string speakAudioContentType = default(string), string errorMessage = default(string))
        {
            this.Successful = successful;
            this.AsyncJobStatus = asyncJobStatus;
            this.AsyncJobID = asyncJobID;
            this.RecognizeResult = recognizeResult;
            this.RecognizeAdvancedResult = recognizeAdvancedResult;
            this.SpeakAudioResultFileContent = speakAudioResultFileContent;
            this.SpeakAudioContentType = speakAudioContentType;
            this.ErrorMessage = errorMessage;
        }
        
        /// <summary>
        /// True if the operation to check the status of the job was successful, false otherwise
        /// </summary>
        /// <value>True if the operation to check the status of the job was successful, false otherwise</value>
        [DataMember(Name="Successful", EmitDefaultValue=false)]
        public bool? Successful { get; set; }

        /// <summary>
        /// Returns the job status of the Async Job, if applicable.  Possible states are STARTED and COMPLETED
        /// </summary>
        /// <value>Returns the job status of the Async Job, if applicable.  Possible states are STARTED and COMPLETED</value>
        [DataMember(Name="AsyncJobStatus", EmitDefaultValue=false)]
        public string AsyncJobStatus { get; set; }

        /// <summary>
        /// Job ID
        /// </summary>
        /// <value>Job ID</value>
        [DataMember(Name="AsyncJobID", EmitDefaultValue=false)]
        public string AsyncJobID { get; set; }

        /// <summary>
        /// Gets or Sets RecognizeResult
        /// </summary>
        [DataMember(Name="RecognizeResult", EmitDefaultValue=false)]
        public SpeechRecognitionResult RecognizeResult { get; set; }

        /// <summary>
        /// Gets or Sets RecognizeAdvancedResult
        /// </summary>
        [DataMember(Name="RecognizeAdvancedResult", EmitDefaultValue=false)]
        public SpeechRecognitionResultAdvanced RecognizeAdvancedResult { get; set; }

        /// <summary>
        /// Generated audio file produced by a completed Text-to-Speech batch job, in the requested format (mp3 or wav)
        /// </summary>
        /// <value>Generated audio file produced by a completed Text-to-Speech batch job, in the requested format (mp3 or wav)</value>
        [DataMember(Name="SpeakAudioResultFileContent", EmitDefaultValue=false)]
        public byte[] SpeakAudioResultFileContent { get; set; }

        /// <summary>
        /// MIME type of SpeakAudioResultFileContent (audio/mpeg or audio/wav)
        /// </summary>
        /// <value>MIME type of SpeakAudioResultFileContent (audio/mpeg or audio/wav)</value>
        [DataMember(Name="SpeakAudioContentType", EmitDefaultValue=false)]
        public string SpeakAudioContentType { get; set; }

        /// <summary>
        /// Error message (if any)
        /// </summary>
        /// <value>Error message (if any)</value>
        [DataMember(Name="ErrorMessage", EmitDefaultValue=false)]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SpeechBatchJobStatusResult {\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  AsyncJobStatus: ").Append(AsyncJobStatus).Append("\n");
            sb.Append("  AsyncJobID: ").Append(AsyncJobID).Append("\n");
            sb.Append("  RecognizeResult: ").Append(RecognizeResult).Append("\n");
            sb.Append("  RecognizeAdvancedResult: ").Append(RecognizeAdvancedResult).Append("\n");
            sb.Append("  SpeakAudioResultFileContent: ").Append(SpeakAudioResultFileContent).Append("\n");
            sb.Append("  SpeakAudioContentType: ").Append(SpeakAudioContentType).Append("\n");
            sb.Append("  ErrorMessage: ").Append(ErrorMessage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SpeechBatchJobStatusResult);
        }

        /// <summary>
        /// Returns true if SpeechBatchJobStatusResult instances are equal
        /// </summary>
        /// <param name="input">Instance of SpeechBatchJobStatusResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SpeechBatchJobStatusResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Successful == input.Successful ||
                    (this.Successful != null &&
                    this.Successful.Equals(input.Successful))
                ) && 
                (
                    this.AsyncJobStatus == input.AsyncJobStatus ||
                    (this.AsyncJobStatus != null &&
                    this.AsyncJobStatus.Equals(input.AsyncJobStatus))
                ) && 
                (
                    this.AsyncJobID == input.AsyncJobID ||
                    (this.AsyncJobID != null &&
                    this.AsyncJobID.Equals(input.AsyncJobID))
                ) && 
                (
                    this.RecognizeResult == input.RecognizeResult ||
                    (this.RecognizeResult != null &&
                    this.RecognizeResult.Equals(input.RecognizeResult))
                ) && 
                (
                    this.RecognizeAdvancedResult == input.RecognizeAdvancedResult ||
                    (this.RecognizeAdvancedResult != null &&
                    this.RecognizeAdvancedResult.Equals(input.RecognizeAdvancedResult))
                ) && 
                (
                    this.SpeakAudioResultFileContent == input.SpeakAudioResultFileContent ||
                    (this.SpeakAudioResultFileContent != null &&
                    this.SpeakAudioResultFileContent.Equals(input.SpeakAudioResultFileContent))
                ) && 
                (
                    this.SpeakAudioContentType == input.SpeakAudioContentType ||
                    (this.SpeakAudioContentType != null &&
                    this.SpeakAudioContentType.Equals(input.SpeakAudioContentType))
                ) && 
                (
                    this.ErrorMessage == input.ErrorMessage ||
                    (this.ErrorMessage != null &&
                    this.ErrorMessage.Equals(input.ErrorMessage))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Successful != null)
                    hashCode = hashCode * 59 + this.Successful.GetHashCode();
                if (this.AsyncJobStatus != null)
                    hashCode = hashCode * 59 + this.AsyncJobStatus.GetHashCode();
                if (this.AsyncJobID != null)
                    hashCode = hashCode * 59 + this.AsyncJobID.GetHashCode();
                if (this.RecognizeResult != null)
                    hashCode = hashCode * 59 + this.RecognizeResult.GetHashCode();
                if (this.RecognizeAdvancedResult != null)
                    hashCode = hashCode * 59 + this.RecognizeAdvancedResult.GetHashCode();
                if (this.SpeakAudioResultFileContent != null)
                    hashCode = hashCode * 59 + this.SpeakAudioResultFileContent.GetHashCode();
                if (this.SpeakAudioContentType != null)
                    hashCode = hashCode * 59 + this.SpeakAudioContentType.GetHashCode();
                if (this.ErrorMessage != null)
                    hashCode = hashCode * 59 + this.ErrorMessage.GetHashCode();
                return hashCode;
            }
        }
    }

}
