/* 
 * speechapi
 *
 * Speech APIs enable you to recognize speech and convert it to text using advanced machine learning, and also to convert text to speech.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.Speech.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.Speech.Model
{
    /// <summary>
    /// Input to a text-to-speech request
    /// </summary>
    [DataContract]
    public partial class TextToSpeechRequest :  IEquatable<TextToSpeechRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TextToSpeechRequest" /> class.
        /// </summary>
        /// <param name="text">Text to be converted to speech.</param>
        /// <param name="format">File format for output audio file: wav or mp3, default is mp3.</param>
        /// <param name="languageCode">ISO 639-3 three-letter language code (e.g. eng, spa, fra, hin, ita, jpn, por, zho). Default is eng (English)..</param>
        /// <param name="gender">Voice gender: Male or Female. Default is Female. Note: Male is not available for French and Chinese..</param>
        public TextToSpeechRequest(string text = default(string), string format = default(string), string languageCode = default(string), string gender = default(string))
        {
            this.Text = text;
            this.Format = format;
            this.LanguageCode = languageCode;
            this.Gender = gender;
        }
        
        /// <summary>
        /// Text to be converted to speech
        /// </summary>
        /// <value>Text to be converted to speech</value>
        [DataMember(Name="Text", EmitDefaultValue=false)]
        public string Text { get; set; }

        /// <summary>
        /// File format for output audio file: wav or mp3, default is mp3
        /// </summary>
        /// <value>File format for output audio file: wav or mp3, default is mp3</value>
        [DataMember(Name="Format", EmitDefaultValue=false)]
        public string Format { get; set; }

        /// <summary>
        /// ISO 639-3 three-letter language code (e.g. eng, spa, fra, hin, ita, jpn, por, zho). Default is eng (English).
        /// </summary>
        /// <value>ISO 639-3 three-letter language code (e.g. eng, spa, fra, hin, ita, jpn, por, zho). Default is eng (English).</value>
        [DataMember(Name="LanguageCode", EmitDefaultValue=false)]
        public string LanguageCode { get; set; }

        /// <summary>
        /// Voice gender: Male or Female. Default is Female. Note: Male is not available for French and Chinese.
        /// </summary>
        /// <value>Voice gender: Male or Female. Default is Female. Note: Male is not available for French and Chinese.</value>
        [DataMember(Name="Gender", EmitDefaultValue=false)]
        public string Gender { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TextToSpeechRequest {\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Format: ").Append(Format).Append("\n");
            sb.Append("  LanguageCode: ").Append(LanguageCode).Append("\n");
            sb.Append("  Gender: ").Append(Gender).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TextToSpeechRequest);
        }

        /// <summary>
        /// Returns true if TextToSpeechRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of TextToSpeechRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TextToSpeechRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Text == input.Text ||
                    (this.Text != null &&
                    this.Text.Equals(input.Text))
                ) && 
                (
                    this.Format == input.Format ||
                    (this.Format != null &&
                    this.Format.Equals(input.Format))
                ) && 
                (
                    this.LanguageCode == input.LanguageCode ||
                    (this.LanguageCode != null &&
                    this.LanguageCode.Equals(input.LanguageCode))
                ) && 
                (
                    this.Gender == input.Gender ||
                    (this.Gender != null &&
                    this.Gender.Equals(input.Gender))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Text != null)
                    hashCode = hashCode * 59 + this.Text.GetHashCode();
                if (this.Format != null)
                    hashCode = hashCode * 59 + this.Format.GetHashCode();
                if (this.LanguageCode != null)
                    hashCode = hashCode * 59 + this.LanguageCode.GetHashCode();
                if (this.Gender != null)
                    hashCode = hashCode * 59 + this.Gender.GetHashCode();
                return hashCode;
            }
        }
    }

}
