/* 
 * speechapi
 *
 * Speech APIs enable you to recognize speech and convert it to text using advanced machine learning, and also to convert text to speech.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.Speech.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.Speech.Model
{
    /// <summary>
    /// A single word with its DTW-aligned time range and position in the output text.
    /// </summary>
    [DataContract]
    public partial class WordTimestamp :  IEquatable<WordTimestamp>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WordTimestamp" /> class.
        /// </summary>
        /// <param name="word">The word text.</param>
        /// <param name="characterOffsetStart">Start character offset (0-based) in TextResult.</param>
        /// <param name="characterOffsetEnd">End character offset (exclusive) in TextResult.</param>
        /// <param name="startTimeMs">Start time of this word in the audio, in milliseconds.</param>
        /// <param name="endTimeMs">End time of this word in the audio, in milliseconds.</param>
        public WordTimestamp(string word = default(string), int? characterOffsetStart = default(int?), int? characterOffsetEnd = default(int?), long? startTimeMs = default(long?), long? endTimeMs = default(long?))
        {
            this.Word = word;
            this.CharacterOffsetStart = characterOffsetStart;
            this.CharacterOffsetEnd = characterOffsetEnd;
            this.StartTimeMs = startTimeMs;
            this.EndTimeMs = endTimeMs;
        }
        
        /// <summary>
        /// The word text
        /// </summary>
        /// <value>The word text</value>
        [DataMember(Name="Word", EmitDefaultValue=false)]
        public string Word { get; set; }

        /// <summary>
        /// Start character offset (0-based) in TextResult
        /// </summary>
        /// <value>Start character offset (0-based) in TextResult</value>
        [DataMember(Name="CharacterOffsetStart", EmitDefaultValue=false)]
        public int? CharacterOffsetStart { get; set; }

        /// <summary>
        /// End character offset (exclusive) in TextResult
        /// </summary>
        /// <value>End character offset (exclusive) in TextResult</value>
        [DataMember(Name="CharacterOffsetEnd", EmitDefaultValue=false)]
        public int? CharacterOffsetEnd { get; set; }

        /// <summary>
        /// Start time of this word in the audio, in milliseconds
        /// </summary>
        /// <value>Start time of this word in the audio, in milliseconds</value>
        [DataMember(Name="StartTimeMs", EmitDefaultValue=false)]
        public long? StartTimeMs { get; set; }

        /// <summary>
        /// End time of this word in the audio, in milliseconds
        /// </summary>
        /// <value>End time of this word in the audio, in milliseconds</value>
        [DataMember(Name="EndTimeMs", EmitDefaultValue=false)]
        public long? EndTimeMs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WordTimestamp {\n");
            sb.Append("  Word: ").Append(Word).Append("\n");
            sb.Append("  CharacterOffsetStart: ").Append(CharacterOffsetStart).Append("\n");
            sb.Append("  CharacterOffsetEnd: ").Append(CharacterOffsetEnd).Append("\n");
            sb.Append("  StartTimeMs: ").Append(StartTimeMs).Append("\n");
            sb.Append("  EndTimeMs: ").Append(EndTimeMs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WordTimestamp);
        }

        /// <summary>
        /// Returns true if WordTimestamp instances are equal
        /// </summary>
        /// <param name="input">Instance of WordTimestamp to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WordTimestamp input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Word == input.Word ||
                    (this.Word != null &&
                    this.Word.Equals(input.Word))
                ) && 
                (
                    this.CharacterOffsetStart == input.CharacterOffsetStart ||
                    (this.CharacterOffsetStart != null &&
                    this.CharacterOffsetStart.Equals(input.CharacterOffsetStart))
                ) && 
                (
                    this.CharacterOffsetEnd == input.CharacterOffsetEnd ||
                    (this.CharacterOffsetEnd != null &&
                    this.CharacterOffsetEnd.Equals(input.CharacterOffsetEnd))
                ) && 
                (
                    this.StartTimeMs == input.StartTimeMs ||
                    (this.StartTimeMs != null &&
                    this.StartTimeMs.Equals(input.StartTimeMs))
                ) && 
                (
                    this.EndTimeMs == input.EndTimeMs ||
                    (this.EndTimeMs != null &&
                    this.EndTimeMs.Equals(input.EndTimeMs))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Word != null)
                    hashCode = hashCode * 59 + this.Word.GetHashCode();
                if (this.CharacterOffsetStart != null)
                    hashCode = hashCode * 59 + this.CharacterOffsetStart.GetHashCode();
                if (this.CharacterOffsetEnd != null)
                    hashCode = hashCode * 59 + this.CharacterOffsetEnd.GetHashCode();
                if (this.StartTimeMs != null)
                    hashCode = hashCode * 59 + this.StartTimeMs.GetHashCode();
                if (this.EndTimeMs != null)
                    hashCode = hashCode * 59 + this.EndTimeMs.GetHashCode();
                return hashCode;
            }
        }
    }

}
