/* 
 * speechapi
 *
 * Speech APIs enable you to recognize speech and convert it to text using advanced machine learning, and also to convert text to speech.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using Cloudmersive.APIClient.NETCore.Speech.Client;
using Cloudmersive.APIClient.NETCore.Speech.Model;

namespace Cloudmersive.APIClient.NETCore.Speech.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITasksBatchJobApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Recognize audio input as text using Advanced AI with high-accuracy word-level timestamps as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for transcribing a long audio file with high-accuracy word-level timestamps.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Higher-accuracy variant of /speech/batch-job/recognize/file. Uses advanced alignment for token timestamps.  Supports WAV, MP3, M4A, FLAC, OGG, and WMA formats.  Consumes 1 API call per second of audio in Fast mode, 5 API calls per second in Normal mode, and 10 API calls per second in Advanced mode.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="languageCode">ISO 639-3 three-letter language code (e.g. eng, spa, fra). Empty for auto-detect. (optional)</param>
        /// <param name="recognitionMode">Recognition mode: Fast, Normal (default), or Advanced. Advanced is only available on Private Cloud and Managed Instance deployments. (optional, default to Normal)</param>
        /// <param name="speechFile"> (optional)</param>
        /// <returns>SpeechBatchJobResult</returns>
        SpeechBatchJobResult SpeechBatchJobRecognizeFileAdvancedPost (string languageCode = null, string recognitionMode = null, System.IO.Stream speechFile = null);

        /// <summary>
        /// Recognize audio input as text using Advanced AI with high-accuracy word-level timestamps as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for transcribing a long audio file with high-accuracy word-level timestamps.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Higher-accuracy variant of /speech/batch-job/recognize/file. Uses advanced alignment for token timestamps.  Supports WAV, MP3, M4A, FLAC, OGG, and WMA formats.  Consumes 1 API call per second of audio in Fast mode, 5 API calls per second in Normal mode, and 10 API calls per second in Advanced mode.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="languageCode">ISO 639-3 three-letter language code (e.g. eng, spa, fra). Empty for auto-detect. (optional)</param>
        /// <param name="recognitionMode">Recognition mode: Fast, Normal (default), or Advanced. Advanced is only available on Private Cloud and Managed Instance deployments. (optional, default to Normal)</param>
        /// <param name="speechFile"> (optional)</param>
        /// <returns>ApiResponse of SpeechBatchJobResult</returns>
        ApiResponse<SpeechBatchJobResult> SpeechBatchJobRecognizeFileAdvancedPostWithHttpInfo (string languageCode = null, string recognitionMode = null, System.IO.Stream speechFile = null);
        /// <summary>
        /// Recognize audio input as text using Advanced AI as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for transcribing a long audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Uses advanced AI to convert input audio to text.  Supports WAV, MP3, M4A, FLAC, OGG, and WMA formats.  Consumes 1 API call per second of audio in Fast mode, 5 API calls per second in Normal mode, and 10 API calls per second in Advanced mode.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="languageCode">ISO 639-3 three-letter language code (e.g. eng, spa, fra). Empty for auto-detect. (optional)</param>
        /// <param name="recognitionMode">Recognition mode: Fast, Normal (default), or Advanced. Advanced is only available on Private Cloud and Managed Instance deployments. (optional, default to Normal)</param>
        /// <param name="speechFile"> (optional)</param>
        /// <returns>SpeechBatchJobResult</returns>
        SpeechBatchJobResult SpeechBatchJobRecognizeFilePost (string languageCode = null, string recognitionMode = null, System.IO.Stream speechFile = null);

        /// <summary>
        /// Recognize audio input as text using Advanced AI as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for transcribing a long audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Uses advanced AI to convert input audio to text.  Supports WAV, MP3, M4A, FLAC, OGG, and WMA formats.  Consumes 1 API call per second of audio in Fast mode, 5 API calls per second in Normal mode, and 10 API calls per second in Advanced mode.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="languageCode">ISO 639-3 three-letter language code (e.g. eng, spa, fra). Empty for auto-detect. (optional)</param>
        /// <param name="recognitionMode">Recognition mode: Fast, Normal (default), or Advanced. Advanced is only available on Private Cloud and Managed Instance deployments. (optional, default to Normal)</param>
        /// <param name="speechFile"> (optional)</param>
        /// <returns>ApiResponse of SpeechBatchJobResult</returns>
        ApiResponse<SpeechBatchJobResult> SpeechBatchJobRecognizeFilePostWithHttpInfo (string languageCode = null, string recognitionMode = null, System.IO.Stream speechFile = null);
        /// <summary>
        /// Generate audio from text using Advanced AI as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for converting long-form text to speech.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the generated audio when complete.  Converts text to speech using advanced AI.  Supports English, Spanish, French, Hindi, Italian, Japanese, Portuguese, and Chinese.  Specify language with LanguageCode (ISO 639-3, default: eng) and gender with Gender (Male or Female, default: Female).  Output format is controlled by the Format field (mp3 or wav, default: mp3).  Consumes 1 API call per second of generated audio.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">String input request (optional)</param>
        /// <returns>SpeechBatchJobResult</returns>
        SpeechBatchJobResult SpeechBatchJobSpeakTextVoiceBasicAudioPost (TextToSpeechRequest body = null);

        /// <summary>
        /// Generate audio from text using Advanced AI as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for converting long-form text to speech.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the generated audio when complete.  Converts text to speech using advanced AI.  Supports English, Spanish, French, Hindi, Italian, Japanese, Portuguese, and Chinese.  Specify language with LanguageCode (ISO 639-3, default: eng) and gender with Gender (Male or Female, default: Female).  Output format is controlled by the Format field (mp3 or wav, default: mp3).  Consumes 1 API call per second of generated audio.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">String input request (optional)</param>
        /// <returns>ApiResponse of SpeechBatchJobResult</returns>
        ApiResponse<SpeechBatchJobResult> SpeechBatchJobSpeakTextVoiceBasicAudioPostWithHttpInfo (TextToSpeechRequest body = null);
        /// <summary>
        /// Get the status and result of a Speech Batch Job
        /// </summary>
        /// <remarks>
        /// Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (Recognize transcription, or generated Text-to-Speech audio) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <returns>SpeechBatchJobStatusResult</returns>
        SpeechBatchJobStatusResult SpeechBatchJobStatusGet (string asyncJobID = null);

        /// <summary>
        /// Get the status and result of a Speech Batch Job
        /// </summary>
        /// <remarks>
        /// Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (Recognize transcription, or generated Text-to-Speech audio) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <returns>ApiResponse of SpeechBatchJobStatusResult</returns>
        ApiResponse<SpeechBatchJobStatusResult> SpeechBatchJobStatusGetWithHttpInfo (string asyncJobID = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Recognize audio input as text using Advanced AI with high-accuracy word-level timestamps as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for transcribing a long audio file with high-accuracy word-level timestamps.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Higher-accuracy variant of /speech/batch-job/recognize/file. Uses advanced alignment for token timestamps.  Supports WAV, MP3, M4A, FLAC, OGG, and WMA formats.  Consumes 1 API call per second of audio in Fast mode, 5 API calls per second in Normal mode, and 10 API calls per second in Advanced mode.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="languageCode">ISO 639-3 three-letter language code (e.g. eng, spa, fra). Empty for auto-detect. (optional)</param>
        /// <param name="recognitionMode">Recognition mode: Fast, Normal (default), or Advanced. Advanced is only available on Private Cloud and Managed Instance deployments. (optional, default to Normal)</param>
        /// <param name="speechFile"> (optional)</param>
        /// <returns>Task of SpeechBatchJobResult</returns>
        System.Threading.Tasks.Task<SpeechBatchJobResult> SpeechBatchJobRecognizeFileAdvancedPostAsync (string languageCode = null, string recognitionMode = null, System.IO.Stream speechFile = null);

        /// <summary>
        /// Recognize audio input as text using Advanced AI with high-accuracy word-level timestamps as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for transcribing a long audio file with high-accuracy word-level timestamps.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Higher-accuracy variant of /speech/batch-job/recognize/file. Uses advanced alignment for token timestamps.  Supports WAV, MP3, M4A, FLAC, OGG, and WMA formats.  Consumes 1 API call per second of audio in Fast mode, 5 API calls per second in Normal mode, and 10 API calls per second in Advanced mode.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="languageCode">ISO 639-3 three-letter language code (e.g. eng, spa, fra). Empty for auto-detect. (optional)</param>
        /// <param name="recognitionMode">Recognition mode: Fast, Normal (default), or Advanced. Advanced is only available on Private Cloud and Managed Instance deployments. (optional, default to Normal)</param>
        /// <param name="speechFile"> (optional)</param>
        /// <returns>Task of ApiResponse (SpeechBatchJobResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<SpeechBatchJobResult>> SpeechBatchJobRecognizeFileAdvancedPostAsyncWithHttpInfo (string languageCode = null, string recognitionMode = null, System.IO.Stream speechFile = null);
        /// <summary>
        /// Recognize audio input as text using Advanced AI as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for transcribing a long audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Uses advanced AI to convert input audio to text.  Supports WAV, MP3, M4A, FLAC, OGG, and WMA formats.  Consumes 1 API call per second of audio in Fast mode, 5 API calls per second in Normal mode, and 10 API calls per second in Advanced mode.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="languageCode">ISO 639-3 three-letter language code (e.g. eng, spa, fra). Empty for auto-detect. (optional)</param>
        /// <param name="recognitionMode">Recognition mode: Fast, Normal (default), or Advanced. Advanced is only available on Private Cloud and Managed Instance deployments. (optional, default to Normal)</param>
        /// <param name="speechFile"> (optional)</param>
        /// <returns>Task of SpeechBatchJobResult</returns>
        System.Threading.Tasks.Task<SpeechBatchJobResult> SpeechBatchJobRecognizeFilePostAsync (string languageCode = null, string recognitionMode = null, System.IO.Stream speechFile = null);

        /// <summary>
        /// Recognize audio input as text using Advanced AI as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for transcribing a long audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Uses advanced AI to convert input audio to text.  Supports WAV, MP3, M4A, FLAC, OGG, and WMA formats.  Consumes 1 API call per second of audio in Fast mode, 5 API calls per second in Normal mode, and 10 API calls per second in Advanced mode.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="languageCode">ISO 639-3 three-letter language code (e.g. eng, spa, fra). Empty for auto-detect. (optional)</param>
        /// <param name="recognitionMode">Recognition mode: Fast, Normal (default), or Advanced. Advanced is only available on Private Cloud and Managed Instance deployments. (optional, default to Normal)</param>
        /// <param name="speechFile"> (optional)</param>
        /// <returns>Task of ApiResponse (SpeechBatchJobResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<SpeechBatchJobResult>> SpeechBatchJobRecognizeFilePostAsyncWithHttpInfo (string languageCode = null, string recognitionMode = null, System.IO.Stream speechFile = null);
        /// <summary>
        /// Generate audio from text using Advanced AI as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for converting long-form text to speech.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the generated audio when complete.  Converts text to speech using advanced AI.  Supports English, Spanish, French, Hindi, Italian, Japanese, Portuguese, and Chinese.  Specify language with LanguageCode (ISO 639-3, default: eng) and gender with Gender (Male or Female, default: Female).  Output format is controlled by the Format field (mp3 or wav, default: mp3).  Consumes 1 API call per second of generated audio.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">String input request (optional)</param>
        /// <returns>Task of SpeechBatchJobResult</returns>
        System.Threading.Tasks.Task<SpeechBatchJobResult> SpeechBatchJobSpeakTextVoiceBasicAudioPostAsync (TextToSpeechRequest body = null);

        /// <summary>
        /// Generate audio from text using Advanced AI as a Batch Job
        /// </summary>
        /// <remarks>
        /// Creates an async batch job for converting long-form text to speech.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the generated audio when complete.  Converts text to speech using advanced AI.  Supports English, Spanish, French, Hindi, Italian, Japanese, Portuguese, and Chinese.  Specify language with LanguageCode (ISO 639-3, default: eng) and gender with Gender (Male or Female, default: Female).  Output format is controlled by the Format field (mp3 or wav, default: mp3).  Consumes 1 API call per second of generated audio.  Requires Managed Instance or Private Cloud deployment.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">String input request (optional)</param>
        /// <returns>Task of ApiResponse (SpeechBatchJobResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<SpeechBatchJobResult>> SpeechBatchJobSpeakTextVoiceBasicAudioPostAsyncWithHttpInfo (TextToSpeechRequest body = null);
        /// <summary>
        /// Get the status and result of a Speech Batch Job
        /// </summary>
        /// <remarks>
        /// Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (Recognize transcription, or generated Text-to-Speech audio) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <returns>Task of SpeechBatchJobStatusResult</returns>
        System.Threading.Tasks.Task<SpeechBatchJobStatusResult> SpeechBatchJobStatusGetAsync (string asyncJobID = null);

        /// <summary>
        /// Get the status and result of a Speech Batch Job
        /// </summary>
        /// <remarks>
        /// Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (Recognize transcription, or generated Text-to-Speech audio) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <returns>Task of ApiResponse (SpeechBatchJobStatusResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<SpeechBatchJobStatusResult>> SpeechBatchJobStatusGetAsyncWithHttpInfo (string asyncJobID = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TasksBatchJobApi : ITasksBatchJobApi
    {
        private Cloudmersive.APIClient.NETCore.Speech.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TasksBatchJobApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TasksBatchJobApi(String basePath)
        {
            this.Configuration = new Cloudmersive.APIClient.NETCore.Speech.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Cloudmersive.APIClient.NETCore.Speech.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TasksBatchJobApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TasksBatchJobApi(Cloudmersive.APIClient.NETCore.Speech.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Cloudmersive.APIClient.NETCore.Speech.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Cloudmersive.APIClient.NETCore.Speech.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Cloudmersive.APIClient.NETCore.Speech.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloudmersive.APIClient.NETCore.Speech.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Recognize audio input as text using Advanced AI with high-accuracy word-level timestamps as a Batch Job Creates an async batch job for transcribing a long audio file with high-accuracy word-level timestamps.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Higher-accuracy variant of /speech/batch-job/recognize/file. Uses advanced alignment for token timestamps.  Supports WAV, MP3, M4A, FLAC, OGG, and WMA formats.  Consumes 1 API call per second of audio in Fast mode, 5 API calls per second in Normal mode, and 10 API calls per second in Advanced mode.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="languageCode">ISO 639-3 three-letter language code (e.g. eng, spa, fra). Empty for auto-detect. (optional)</param>
        /// <param name="recognitionMode">Recognition mode: Fast, Normal (default), or Advanced. Advanced is only available on Private Cloud and Managed Instance deployments. (optional, default to Normal)</param>
        /// <param name="speechFile"> (optional)</param>
        /// <returns>SpeechBatchJobResult</returns>
        public SpeechBatchJobResult SpeechBatchJobRecognizeFileAdvancedPost (string languageCode = null, string recognitionMode = null, System.IO.Stream speechFile = null)
        {
             ApiResponse<SpeechBatchJobResult> localVarResponse = SpeechBatchJobRecognizeFileAdvancedPostWithHttpInfo(languageCode, recognitionMode, speechFile);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Recognize audio input as text using Advanced AI with high-accuracy word-level timestamps as a Batch Job Creates an async batch job for transcribing a long audio file with high-accuracy word-level timestamps.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Higher-accuracy variant of /speech/batch-job/recognize/file. Uses advanced alignment for token timestamps.  Supports WAV, MP3, M4A, FLAC, OGG, and WMA formats.  Consumes 1 API call per second of audio in Fast mode, 5 API calls per second in Normal mode, and 10 API calls per second in Advanced mode.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="languageCode">ISO 639-3 three-letter language code (e.g. eng, spa, fra). Empty for auto-detect. (optional)</param>
        /// <param name="recognitionMode">Recognition mode: Fast, Normal (default), or Advanced. Advanced is only available on Private Cloud and Managed Instance deployments. (optional, default to Normal)</param>
        /// <param name="speechFile"> (optional)</param>
        /// <returns>ApiResponse of SpeechBatchJobResult</returns>
        public ApiResponse< SpeechBatchJobResult > SpeechBatchJobRecognizeFileAdvancedPostWithHttpInfo (string languageCode = null, string recognitionMode = null, System.IO.Stream speechFile = null)
        {

            var localVarPath = "./speech/batch-job/recognize/file/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (languageCode != null) localVarHeaderParams.Add("languageCode", this.Configuration.ApiClient.ParameterToString(languageCode)); // header parameter
            if (recognitionMode != null) localVarHeaderParams.Add("recognitionMode", this.Configuration.ApiClient.ParameterToString(recognitionMode)); // header parameter
            if (speechFile != null) localVarFileParams.Add("speechFile", this.Configuration.ApiClient.ParameterToFile("speechFile", speechFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SpeechBatchJobRecognizeFileAdvancedPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpeechBatchJobResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (SpeechBatchJobResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpeechBatchJobResult)));
        }

        /// <summary>
        /// Recognize audio input as text using Advanced AI with high-accuracy word-level timestamps as a Batch Job Creates an async batch job for transcribing a long audio file with high-accuracy word-level timestamps.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Higher-accuracy variant of /speech/batch-job/recognize/file. Uses advanced alignment for token timestamps.  Supports WAV, MP3, M4A, FLAC, OGG, and WMA formats.  Consumes 1 API call per second of audio in Fast mode, 5 API calls per second in Normal mode, and 10 API calls per second in Advanced mode.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="languageCode">ISO 639-3 three-letter language code (e.g. eng, spa, fra). Empty for auto-detect. (optional)</param>
        /// <param name="recognitionMode">Recognition mode: Fast, Normal (default), or Advanced. Advanced is only available on Private Cloud and Managed Instance deployments. (optional, default to Normal)</param>
        /// <param name="speechFile"> (optional)</param>
        /// <returns>Task of SpeechBatchJobResult</returns>
        public async System.Threading.Tasks.Task<SpeechBatchJobResult> SpeechBatchJobRecognizeFileAdvancedPostAsync (string languageCode = null, string recognitionMode = null, System.IO.Stream speechFile = null)
        {
             ApiResponse<SpeechBatchJobResult> localVarResponse = await SpeechBatchJobRecognizeFileAdvancedPostAsyncWithHttpInfo(languageCode, recognitionMode, speechFile);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Recognize audio input as text using Advanced AI with high-accuracy word-level timestamps as a Batch Job Creates an async batch job for transcribing a long audio file with high-accuracy word-level timestamps.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Higher-accuracy variant of /speech/batch-job/recognize/file. Uses advanced alignment for token timestamps.  Supports WAV, MP3, M4A, FLAC, OGG, and WMA formats.  Consumes 1 API call per second of audio in Fast mode, 5 API calls per second in Normal mode, and 10 API calls per second in Advanced mode.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="languageCode">ISO 639-3 three-letter language code (e.g. eng, spa, fra). Empty for auto-detect. (optional)</param>
        /// <param name="recognitionMode">Recognition mode: Fast, Normal (default), or Advanced. Advanced is only available on Private Cloud and Managed Instance deployments. (optional, default to Normal)</param>
        /// <param name="speechFile"> (optional)</param>
        /// <returns>Task of ApiResponse (SpeechBatchJobResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SpeechBatchJobResult>> SpeechBatchJobRecognizeFileAdvancedPostAsyncWithHttpInfo (string languageCode = null, string recognitionMode = null, System.IO.Stream speechFile = null)
        {

            var localVarPath = "./speech/batch-job/recognize/file/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (languageCode != null) localVarHeaderParams.Add("languageCode", this.Configuration.ApiClient.ParameterToString(languageCode)); // header parameter
            if (recognitionMode != null) localVarHeaderParams.Add("recognitionMode", this.Configuration.ApiClient.ParameterToString(recognitionMode)); // header parameter
            if (speechFile != null) localVarFileParams.Add("speechFile", this.Configuration.ApiClient.ParameterToFile("speechFile", speechFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SpeechBatchJobRecognizeFileAdvancedPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpeechBatchJobResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (SpeechBatchJobResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpeechBatchJobResult)));
        }

        /// <summary>
        /// Recognize audio input as text using Advanced AI as a Batch Job Creates an async batch job for transcribing a long audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Uses advanced AI to convert input audio to text.  Supports WAV, MP3, M4A, FLAC, OGG, and WMA formats.  Consumes 1 API call per second of audio in Fast mode, 5 API calls per second in Normal mode, and 10 API calls per second in Advanced mode.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="languageCode">ISO 639-3 three-letter language code (e.g. eng, spa, fra). Empty for auto-detect. (optional)</param>
        /// <param name="recognitionMode">Recognition mode: Fast, Normal (default), or Advanced. Advanced is only available on Private Cloud and Managed Instance deployments. (optional, default to Normal)</param>
        /// <param name="speechFile"> (optional)</param>
        /// <returns>SpeechBatchJobResult</returns>
        public SpeechBatchJobResult SpeechBatchJobRecognizeFilePost (string languageCode = null, string recognitionMode = null, System.IO.Stream speechFile = null)
        {
             ApiResponse<SpeechBatchJobResult> localVarResponse = SpeechBatchJobRecognizeFilePostWithHttpInfo(languageCode, recognitionMode, speechFile);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Recognize audio input as text using Advanced AI as a Batch Job Creates an async batch job for transcribing a long audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Uses advanced AI to convert input audio to text.  Supports WAV, MP3, M4A, FLAC, OGG, and WMA formats.  Consumes 1 API call per second of audio in Fast mode, 5 API calls per second in Normal mode, and 10 API calls per second in Advanced mode.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="languageCode">ISO 639-3 three-letter language code (e.g. eng, spa, fra). Empty for auto-detect. (optional)</param>
        /// <param name="recognitionMode">Recognition mode: Fast, Normal (default), or Advanced. Advanced is only available on Private Cloud and Managed Instance deployments. (optional, default to Normal)</param>
        /// <param name="speechFile"> (optional)</param>
        /// <returns>ApiResponse of SpeechBatchJobResult</returns>
        public ApiResponse< SpeechBatchJobResult > SpeechBatchJobRecognizeFilePostWithHttpInfo (string languageCode = null, string recognitionMode = null, System.IO.Stream speechFile = null)
        {

            var localVarPath = "./speech/batch-job/recognize/file";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (languageCode != null) localVarHeaderParams.Add("languageCode", this.Configuration.ApiClient.ParameterToString(languageCode)); // header parameter
            if (recognitionMode != null) localVarHeaderParams.Add("recognitionMode", this.Configuration.ApiClient.ParameterToString(recognitionMode)); // header parameter
            if (speechFile != null) localVarFileParams.Add("speechFile", this.Configuration.ApiClient.ParameterToFile("speechFile", speechFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SpeechBatchJobRecognizeFilePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpeechBatchJobResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (SpeechBatchJobResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpeechBatchJobResult)));
        }

        /// <summary>
        /// Recognize audio input as text using Advanced AI as a Batch Job Creates an async batch job for transcribing a long audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Uses advanced AI to convert input audio to text.  Supports WAV, MP3, M4A, FLAC, OGG, and WMA formats.  Consumes 1 API call per second of audio in Fast mode, 5 API calls per second in Normal mode, and 10 API calls per second in Advanced mode.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="languageCode">ISO 639-3 three-letter language code (e.g. eng, spa, fra). Empty for auto-detect. (optional)</param>
        /// <param name="recognitionMode">Recognition mode: Fast, Normal (default), or Advanced. Advanced is only available on Private Cloud and Managed Instance deployments. (optional, default to Normal)</param>
        /// <param name="speechFile"> (optional)</param>
        /// <returns>Task of SpeechBatchJobResult</returns>
        public async System.Threading.Tasks.Task<SpeechBatchJobResult> SpeechBatchJobRecognizeFilePostAsync (string languageCode = null, string recognitionMode = null, System.IO.Stream speechFile = null)
        {
             ApiResponse<SpeechBatchJobResult> localVarResponse = await SpeechBatchJobRecognizeFilePostAsyncWithHttpInfo(languageCode, recognitionMode, speechFile);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Recognize audio input as text using Advanced AI as a Batch Job Creates an async batch job for transcribing a long audio file.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the result when complete.  Uses advanced AI to convert input audio to text.  Supports WAV, MP3, M4A, FLAC, OGG, and WMA formats.  Consumes 1 API call per second of audio in Fast mode, 5 API calls per second in Normal mode, and 10 API calls per second in Advanced mode.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="languageCode">ISO 639-3 three-letter language code (e.g. eng, spa, fra). Empty for auto-detect. (optional)</param>
        /// <param name="recognitionMode">Recognition mode: Fast, Normal (default), or Advanced. Advanced is only available on Private Cloud and Managed Instance deployments. (optional, default to Normal)</param>
        /// <param name="speechFile"> (optional)</param>
        /// <returns>Task of ApiResponse (SpeechBatchJobResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SpeechBatchJobResult>> SpeechBatchJobRecognizeFilePostAsyncWithHttpInfo (string languageCode = null, string recognitionMode = null, System.IO.Stream speechFile = null)
        {

            var localVarPath = "./speech/batch-job/recognize/file";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (languageCode != null) localVarHeaderParams.Add("languageCode", this.Configuration.ApiClient.ParameterToString(languageCode)); // header parameter
            if (recognitionMode != null) localVarHeaderParams.Add("recognitionMode", this.Configuration.ApiClient.ParameterToString(recognitionMode)); // header parameter
            if (speechFile != null) localVarFileParams.Add("speechFile", this.Configuration.ApiClient.ParameterToFile("speechFile", speechFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SpeechBatchJobRecognizeFilePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpeechBatchJobResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (SpeechBatchJobResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpeechBatchJobResult)));
        }

        /// <summary>
        /// Generate audio from text using Advanced AI as a Batch Job Creates an async batch job for converting long-form text to speech.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the generated audio when complete.  Converts text to speech using advanced AI.  Supports English, Spanish, French, Hindi, Italian, Japanese, Portuguese, and Chinese.  Specify language with LanguageCode (ISO 639-3, default: eng) and gender with Gender (Male or Female, default: Female).  Output format is controlled by the Format field (mp3 or wav, default: mp3).  Consumes 1 API call per second of generated audio.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">String input request (optional)</param>
        /// <returns>SpeechBatchJobResult</returns>
        public SpeechBatchJobResult SpeechBatchJobSpeakTextVoiceBasicAudioPost (TextToSpeechRequest body = null)
        {
             ApiResponse<SpeechBatchJobResult> localVarResponse = SpeechBatchJobSpeakTextVoiceBasicAudioPostWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Generate audio from text using Advanced AI as a Batch Job Creates an async batch job for converting long-form text to speech.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the generated audio when complete.  Converts text to speech using advanced AI.  Supports English, Spanish, French, Hindi, Italian, Japanese, Portuguese, and Chinese.  Specify language with LanguageCode (ISO 639-3, default: eng) and gender with Gender (Male or Female, default: Female).  Output format is controlled by the Format field (mp3 or wav, default: mp3).  Consumes 1 API call per second of generated audio.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">String input request (optional)</param>
        /// <returns>ApiResponse of SpeechBatchJobResult</returns>
        public ApiResponse< SpeechBatchJobResult > SpeechBatchJobSpeakTextVoiceBasicAudioPostWithHttpInfo (TextToSpeechRequest body = null)
        {

            var localVarPath = "./speech/batch-job/speak/text/voice/basic/audio";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SpeechBatchJobSpeakTextVoiceBasicAudioPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpeechBatchJobResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (SpeechBatchJobResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpeechBatchJobResult)));
        }

        /// <summary>
        /// Generate audio from text using Advanced AI as a Batch Job Creates an async batch job for converting long-form text to speech.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the generated audio when complete.  Converts text to speech using advanced AI.  Supports English, Spanish, French, Hindi, Italian, Japanese, Portuguese, and Chinese.  Specify language with LanguageCode (ISO 639-3, default: eng) and gender with Gender (Male or Female, default: Female).  Output format is controlled by the Format field (mp3 or wav, default: mp3).  Consumes 1 API call per second of generated audio.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">String input request (optional)</param>
        /// <returns>Task of SpeechBatchJobResult</returns>
        public async System.Threading.Tasks.Task<SpeechBatchJobResult> SpeechBatchJobSpeakTextVoiceBasicAudioPostAsync (TextToSpeechRequest body = null)
        {
             ApiResponse<SpeechBatchJobResult> localVarResponse = await SpeechBatchJobSpeakTextVoiceBasicAudioPostAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Generate audio from text using Advanced AI as a Batch Job Creates an async batch job for converting long-form text to speech.  Use the GetAsyncJobStatus API to check on the status of the job and retrieve the generated audio when complete.  Converts text to speech using advanced AI.  Supports English, Spanish, French, Hindi, Italian, Japanese, Portuguese, and Chinese.  Specify language with LanguageCode (ISO 639-3, default: eng) and gender with Gender (Male or Female, default: Female).  Output format is controlled by the Format field (mp3 or wav, default: mp3).  Consumes 1 API call per second of generated audio.  Requires Managed Instance or Private Cloud deployment.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">String input request (optional)</param>
        /// <returns>Task of ApiResponse (SpeechBatchJobResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SpeechBatchJobResult>> SpeechBatchJobSpeakTextVoiceBasicAudioPostAsyncWithHttpInfo (TextToSpeechRequest body = null)
        {

            var localVarPath = "./speech/batch-job/speak/text/voice/basic/audio";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SpeechBatchJobSpeakTextVoiceBasicAudioPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpeechBatchJobResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (SpeechBatchJobResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpeechBatchJobResult)));
        }

        /// <summary>
        /// Get the status and result of a Speech Batch Job Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (Recognize transcription, or generated Text-to-Speech audio) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <returns>SpeechBatchJobStatusResult</returns>
        public SpeechBatchJobStatusResult SpeechBatchJobStatusGet (string asyncJobID = null)
        {
             ApiResponse<SpeechBatchJobStatusResult> localVarResponse = SpeechBatchJobStatusGetWithHttpInfo(asyncJobID);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get the status and result of a Speech Batch Job Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (Recognize transcription, or generated Text-to-Speech audio) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <returns>ApiResponse of SpeechBatchJobStatusResult</returns>
        public ApiResponse< SpeechBatchJobStatusResult > SpeechBatchJobStatusGetWithHttpInfo (string asyncJobID = null)
        {

            var localVarPath = "./speech/batch-job/status";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (asyncJobID != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "AsyncJobID", asyncJobID)); // query parameter

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SpeechBatchJobStatusGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpeechBatchJobStatusResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (SpeechBatchJobStatusResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpeechBatchJobStatusResult)));
        }

        /// <summary>
        /// Get the status and result of a Speech Batch Job Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (Recognize transcription, or generated Text-to-Speech audio) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <returns>Task of SpeechBatchJobStatusResult</returns>
        public async System.Threading.Tasks.Task<SpeechBatchJobStatusResult> SpeechBatchJobStatusGetAsync (string asyncJobID = null)
        {
             ApiResponse<SpeechBatchJobStatusResult> localVarResponse = await SpeechBatchJobStatusGetAsyncWithHttpInfo(asyncJobID);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get the status and result of a Speech Batch Job Returns the result of the Async Job - possible states can be STARTED or COMPLETED.  When COMPLETED, the corresponding result field (Recognize transcription, or generated Text-to-Speech audio) is populated on the response.  This API is only available for Cloudmersive Managed Instance and Private Cloud deployments.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Speech.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asyncJobID">Job ID for the batch job to get the status of (optional)</param>
        /// <returns>Task of ApiResponse (SpeechBatchJobStatusResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SpeechBatchJobStatusResult>> SpeechBatchJobStatusGetAsyncWithHttpInfo (string asyncJobID = null)
        {

            var localVarPath = "./speech/batch-job/status";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (asyncJobID != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "AsyncJobID", asyncJobID)); // query parameter

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SpeechBatchJobStatusGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SpeechBatchJobStatusResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (SpeechBatchJobStatusResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SpeechBatchJobStatusResult)));
        }

    }
}
